#! /bin/bash
echo ............................................................
echo Installing composer dependencies
echo ............................................................
composer install --prefer-dist
echo Done!
echo ............................................................
echo Updating composer dependencies
echo ............................................................
composer update --prefer-dist
echo Done!
echo ............................................................
echo Dumping composer autoload --optimize
echo ............................................................
composer dumpautoload
echo Done!
echo ............................................................